# Generated by Django 5.0.6 on 2024-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('salary', models.IntegerField()),
                ('occupation', models.CharField(max_length=25)),
            ],
        ),
    ]
